name: 'people-library-system'
services:
  db:
    container_name: 'people-library-db'
    image: postgres
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_DB=library-db"
      - "POSTGRES_PASSWORD=admin123"
    ports:
      - "5000:5432"
